version: '3.1'

networks:
  default:
    name: grpc_training

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_grpc
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    image: grpc_training_server:v1
    environment:
      DB_HOST: db
    ports:
      - "9090:9090"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    image: grpc_training_client:v1
    environment:
      SERVER_HOST: server
    ports:
      - "9091:9091"
    depends_on:
      - server
    