// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type Car struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Model       string    `json:"model"`
	Color       string    `json:"color"`
	Year        string    `json:"year"`
	Price       string    `json:"price"`
	Image       string    `json:"image"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
