// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCar(ctx context.Context, arg CreateCarParams) (Car, error)
	DeleteCar(ctx context.Context, id uuid.UUID) error
	GetCar(ctx context.Context, id uuid.UUID) (Car, error)
	ListCars(ctx context.Context, limit int32) ([]Car, error)
	UpdateCar(ctx context.Context, arg UpdateCarParams) (Car, error)
}

var _ Querier = (*Queries)(nil)
